# Generated by Django 5.1.4 on 2025-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=255),
        ),
    ]
