# Generated by Django 5.1.4 on 2025-01-14 01:54

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_date_created_account_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsingsession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='browsingsession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=core.models.get_default_profile_image, max_length=255, null=True, upload_to=core.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='browsingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_session', to='core.childprofile'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_start', models.DateTimeField()),
                ('duration_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_schedule', to='core.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_schedule', to='core.parentprofile')),
            ],
        ),
    ]
