# Generated by Django 5.1.4 on 2025-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_browsingsession_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsingsession',
            name='device_id',
            field=models.CharField(max_length=400),
        ),
    ]
