# Generated by Django 5.1.4 on 2025-01-15 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_browsingsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_session', to='core.childprofile'),
        ),
    ]
