# Generated by Django 5.1.4 on 2025-01-16 12:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_allowlist_blocklist_activitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='is_allowed_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='is_global_rules_applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='is_get_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=core.models.get_default_profile_image, max_length=255, null=True, upload_to=core.models.get_profile_image_filepath),
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='allow_list',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='block_list',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='allow_list',
            field=models.ManyToManyField(to='core.allowlist'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='block_list',
            field=models.ManyToManyField(to='core.blocklist'),
        ),
    ]
