# Generated by Django 5.1.4 on 2025-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_childprofile_is_allowed_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='child',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='parent',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='schedule',
            field=models.ManyToManyField(related_name='child_profile', to='core.schedule'),
        ),
    ]
