# Generated by Django 5.1.4 on 2025-01-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_schedule_child_remove_schedule_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='is_allowed_list',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='is_allowed_list',
            field=models.BooleanField(default=False),
        ),
    ]
