# Generated by Django 5.1.4 on 2025-01-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_childprofile_is_allowed_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='child_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.childprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='schedule',
            field=models.ManyToManyField(related_name='+', to='core.schedule'),
        ),
    ]
