# Generated by Django 5.1.4 on 2025-01-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_childprofile_allow_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
