# Generated by Django 5.1.4 on 2025-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_childprofile_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allowlist',
            name='website_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
