# Generated by Django 5.1.4 on 2025-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_allowlist_name_alter_allowlist_website_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='website_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='allowlist',
            name='website_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='website_url',
            field=models.CharField(max_length=1000),
        ),
    ]
