# Generated by Django 5.1.5 on 2025-01-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration_start',
            field=models.TimeField(),
        ),
    ]
