from django.urls import path
from .views import (CustomTokenObtainPairView, CustomRegistrationAPIView,DashboardChildRegistrationAPIView, DashboardChildListAPIView, ChildDeviceIdValidateAPIView, BrowsingSessionStartAPIView, BrowsingHistorySyncAPIView,
                    BrowsingSessionSyncAPIView, DashboardParentSettingsUpdateAPIView, DashboardParentSettingsAllowListCreateAPIView, DashboardParentSettingsAllowListRetrieveAPIView, DashboardParentSettingsAllowListDeleteAPIView, DashboardParentSettingsBlockListCreateAPIView, DashboardParentSettingsBlockListRetrieveAPIView, DashboardParentSettingsBlockListDeleteAPIView, DashboardParentSettingsScheduleCreateAPIView, DashboardParentSettingsScheduleDeleteAPIView, DashboardParentSettingsScheduleRetrieveAPIView, DashboardParentSettingsScheduleUpdateAPIView, DashboardParentChildrenListAPIView, DashboardParentSettingsRetrieveAPIView, DashboardParentSettingsUpdateParentOnlyAPIView, DashboardParentSettingsProfilePictureRetrieveAPIView, DashboardParentSettingsProfilePictureUpdateAPIView, 
                    DashboardChildGlobalRulesUpdateAPIView, DashboardChildActivityLogAPIView, DashboardParentChildrenActivityLogAPIView, DashboardChildUpdateAPIView, DashboardParentChildrenCountAPIView, DashboardParentTotalBlockedTodayAPIView, DashboardParentChildrenTodayActivityAPIView, DashboardParentChildrenRecentActivityAPIView, DashboardParentDailyActivityGraphAPIView, DashboardParentTopBlockedSitesAPIView, UserExtensionParentChildrenListAPIView, UserExtensionChildTodayStatsAPIView, UserExtensionChildRecentActivityAPIView, UserExtensionChildDeviceInfoAPIView, UserExtensionChildScreenTimeAPIView, UserExtensionChildCurrentRestrictionsAPIView, UserExtensionParentEmailAPIView)
urlpatterns = [
    path('user/token/',CustomTokenObtainPairView.as_view()),
    path('user/sign-up/', CustomRegistrationAPIView.as_view()),
    path('user/sign-up/child/', DashboardChildRegistrationAPIView.as_view()),
    path('user/sign-up/child/<int:pk>/', DashboardChildUpdateAPIView.as_view()),
    path('user/login/child/<str:pk>/', ChildDeviceIdValidateAPIView.as_view()),
    
    path('user/dashboard/child/list/<int:pk>/', DashboardChildListAPIView.as_view()),
    
    path('user/browsing/session/start/', BrowsingSessionStartAPIView.as_view()),
    path('user/browsing/session/sync/', BrowsingSessionSyncAPIView.as_view()),
    
    path('user/browsing/history/sync/', BrowsingHistorySyncAPIView.as_view()),
    path('user/dashboard/settings/update/', DashboardParentSettingsUpdateAPIView.as_view()),
    
    path('user/allow-list/', DashboardParentSettingsAllowListCreateAPIView.as_view()),
    
    
    path('user/allow-list/<str:profile_type>/<int:profile_id>/', DashboardParentSettingsAllowListRetrieveAPIView.as_view()),
    path('user/allow-list/<str:profile_type>/<int:profile_id>/<str:website_name>/', DashboardParentSettingsAllowListDeleteAPIView.as_view()),
    
    path('user/block-list/', DashboardParentSettingsBlockListCreateAPIView.as_view()),
    path('user/block-list/<str:profile_type>/<int:profile_id>/', DashboardParentSettingsBlockListRetrieveAPIView.as_view()),
    path('user/block-list/<str:profile_type>/<int:profile_id>/<str:website_name>/', DashboardParentSettingsBlockListDeleteAPIView.as_view()),
    
    # Schedule management endpoints
    path('user/schedule/', DashboardParentSettingsScheduleCreateAPIView.as_view()),
    path('user/schedule/<int:profile_id>/', DashboardParentSettingsScheduleRetrieveAPIView.as_view()),
    path('user/schedule/<int:profile_id>/<int:schedule_id>/', DashboardParentSettingsScheduleDeleteAPIView.as_view()),
    path('user/schedule/<int:profile_id>/<int:schedule_id>/update/', DashboardParentSettingsScheduleUpdateAPIView.as_view()),
    # path('user/forget-password/', UserForgotPasswordView.as_view())
    path('user/dashboard/parent/<int:parent_id>/children/', DashboardParentChildrenListAPIView.as_view()),
    path('user/dashboard/settings/retrieve/', DashboardParentSettingsRetrieveAPIView.as_view()),
    path('user/dashboard/settings/update-parent/', DashboardParentSettingsUpdateParentOnlyAPIView.as_view()),
    path('user/dashboard/settings/profile-picture/<int:parent_id>/', DashboardParentSettingsProfilePictureRetrieveAPIView.as_view()),
    path('user/dashboard/settings/profile-picture/<int:parent_id>/update/', DashboardParentSettingsProfilePictureUpdateAPIView.as_view()),
    path('user/dashboard/child/<int:child_id>/global-rules/', DashboardChildGlobalRulesUpdateAPIView.as_view()),
    path('user/dashboard/child/<int:child_id>/activity-log/', DashboardChildActivityLogAPIView.as_view()),
    path('user/dashboard/parent/<int:parent_id>/children/activity-log/', DashboardParentChildrenActivityLogAPIView.as_view()),
    path('user/dashboard/parent/<int:parent_id>/children/count/', DashboardParentChildrenCountAPIView.as_view(), name='dashboard-parent-children-count'),
    path('user/dashboard/parent/<int:parent_id>/blocked-today/', DashboardParentTotalBlockedTodayAPIView.as_view(), name='dashboard-parent-total-blocked-today'),
    path('user/dashboard/parent/<int:parent_id>/children/today-activity/', 
         DashboardParentChildrenTodayActivityAPIView.as_view(), 
         name='dashboard-parent-children-today-activity'),
    path('user/dashboard/parent/<int:parent_id>/children/recent-activity/', 
         DashboardParentChildrenRecentActivityAPIView.as_view(), 
         name='dashboard-parent-children-recent-activity'),
    path('user/dashboard/parent/<int:parent_id>/daily-activity-graph/', 
         DashboardParentDailyActivityGraphAPIView.as_view(), 
         name='dashboard-parent-daily-activity-graph'),
    path('user/dashboard/parent/<int:parent_id>/top-blocked-sites/', 
         DashboardParentTopBlockedSitesAPIView.as_view(), 
         name='dashboard-parent-top-blocked-sites'),
    path('user/extension/parent/<int:parent_id>/children/', 
         UserExtensionParentChildrenListAPIView.as_view(), 
         name='user-extension-parent-children-list'),
    path('user/extension/child/<int:child_id>/today-stats/', 
         UserExtensionChildTodayStatsAPIView.as_view(), 
         name='user-extension-child-today-stats'),
    path('user/extension/child/<int:child_id>/recent-activity/', 
         UserExtensionChildRecentActivityAPIView.as_view(), 
         name='user-extension-child-recent-activity'),
    path('user/extension/child/device/<str:device_id>/', 
         UserExtensionChildDeviceInfoAPIView.as_view(), 
         name='user-extension-child-device-info'),
    path('user/extension/child/<str:device_id>/screen-time/', 
         UserExtensionChildScreenTimeAPIView.as_view(), 
         name='user-extension-child-screen-time'),
    path('user/extension/child/device/<str:device_id>/restrictions/', 
         UserExtensionChildCurrentRestrictionsAPIView.as_view(), 
         name='user-extension-child-current-restrictions'),
    path('user/extension/child/device/<str:device_id>/parent-email/', 
         UserExtensionParentEmailAPIView.as_view(), 
         name='user-extension-parent-email'),
]